# Generated by Django 5.0.3 on 2024-03-09 18:20

import django.db.models.deletion
import minecraft.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0003_alter_server_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='difficulty_id',
            field=models.ForeignKey(default=minecraft.models.get_default_difficulty, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minecraft.difficulty'),
        ),
    ]
