# Generated by Django 5.0.3 on 2024-03-12 08:49

import django.db.models.deletion
import minecraft.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0004_alter_server_difficulty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='gamemode_id',
            field=models.ForeignKey(default=minecraft.models.get_default_gamemode, null=True, on_delete=django.db.models.deletion.SET_NULL, to='minecraft.gamemode'),
        ),
    ]
