# Generated by Django 5.0.3 on 2024-03-12 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0005_server_owner_alter_server_gamemode_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to=settings.AUTH_USER_MODEL),
        ),
    ]
