# Generated by Django 5.0.3 on 2024-03-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0006_alter_server_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='owner',
        ),
    ]
