# Generated by Django 5.0.3 on 2024-03-13 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0007_remove_server_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(26565), django.core.validators.MinValueValidator(25565)]),
        ),
    ]
