# Generated by Django 5.0.3 on 2024-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minecraft', '0009_alter_server_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='realname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamemode',
            name='realname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
